post_build:
  commands:
    - aws eks update-kubeconfig --region us-east-1 --name claim-cluster
    - kubectl set image deployment/claim-api claim-api=071517866612.dkr.ecr.us-east-1.amazonaws.com/claim-status-api:latest
