apiVersion: v1
kind: Service
metadata:
  name: claim-api-service
spec:
  type: LoadBalancer
  selector:
    app: claim-api
  ports:
    - port: 80
      targetPort: 8080
eksctl-claim-cluster-nodegroup-cla-NodeInstanceRole-vcWWOy6bI4e5